version: '3'

services:
  cms:
    image: ghcr.io/climactivity/climate-friday-backend:latest
    restart: 'always'
    container_name: cms
    environment:
      - VITE_PB_BASE_URL=/
    expose:
      - '8088'
    ports:
      - '8088:8088'
    volumes:
      - ./pb_data:/usr/src/app/pb_data
