version: '3'

services:
  cms:
    build: .
    restart: 'unless-stopped'
    container_name: cms
    expose:
      - '8088'
    environment:
      - VITE_PB_BASE_URL=/
    ports:
      - '8088:8088'
    volumes:
      - ./pb_data:/usr/src/app/pb_data
